config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|es/ do
    root to: 'frontend#index'

    devise_for :users, skip: KepplerConfiguration.skip_module_devise

    resources :admin, only: :index

    get "/eventos" => 'events#new', :as => :new_event
    post "/eventos" => 'events#create', :as => :create_events
    get "/paraguana" => "frontend#paraguana" , as: :paraguana
    get "/instalaciones" => "frontend#facilities" , as: :facilities
    get "/room/:permalink" => 'frontend#show_room' , as: :show_room
    get "/encuesta" => 'frontend#poll', :as => :new_poll
    post "/enviar_encuesta" => 'frontend#send_poll', :as => :send_poll

    scope :admin do
      resources :polls do
        get '/statistics', to: "polls#poll_statistics", as: :statistics
        get '/question/create/:question_type', to: "questions#create", as: :question_create
        delete '/question/delete/:id', to: "questions#delete", as: :question_delete
        get '/question/edit/:id/', to: "questions#edit", as: :question_edit
        delete '/question/:id/delete_option/:option_id', to: "questions#delete_option", as: :question_delete_option
        post '/question/:id/add_option/', to: "questions#add_option", as: :question_add_option
        patch '/question/update/:id/', to: "questions#update", as: :question
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple

        resources :results do
          get '(page/:page)', action: :index, on: :collection, as: ''
          delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
        end
      end

    	resources :users do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :rooms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      get 'clients/export' => 'clients#export', as: :export_clients
      resources :clients do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :events, except: [:new, :create] do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/export', action: :export, as: :export
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :promos do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :event_images do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end


    #errors
    match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
    match '/404', to: 'errors#not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all


    #dashboard
    mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'
  end

end

app/models/result.rb
#Generado por keppler
require 'elasticsearch/model'
class Result < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :poll
  has_many :results_questions, dependent: :destroy

  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      firstname:  self.firstname.to_s,
      lastname:  self.lastname.to_s,
      email:  self.email.to_s,
      poll_id:  self.poll_id.to_s,
    }.as_json
  end

  def fullname
    "#{firstname} #{lastname}"
  end

end
#Result.import

app/controllers/results_controller.rb
#Generado con Keppler.
class ResultsController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_result, only: [:show, :edit, :update, :destroy]
  before_action :set_poll

  # GET /results
  def index
    results = Result.searching(@query).where(poll_id: @poll.id)
    @objects, @total = results.page(@current_page), results.size
    redirect_to results_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /results/1
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  def create
    @result = Result.new(result_params)
    @result.poll_id = @poll.id

    if @result.save
      redirect_to poll_results_path(@poll), notice: 'Result was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /results/1
  def update
    if @result.update(result_params)
      redirect_to poll_results_path(@poll), notice: 'Result was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /results/1
  def destroy
    @result.destroy
    redirect_to poll_results_path(@poll), notice: 'Result was successfully destroyed.'
  end

  def destroy_multiple
    Result.destroy redefine_ids(params[:multiple_ids])
    redirect_to poll_results_path(@poll, page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    def set_poll
      @poll = Poll.find(params[:poll_id])
    end

    # Only allow a trusted parameter "white list" through.
    def result_params
      params.require(:result).permit(:firstname, :lastname, :email, :poll_id)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/results/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to poll_results_path(@poll), class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for [@poll, @result] do |f|
					.row
						= f.input :firstname
						= f.input :lastname
						= f.input :email

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/results/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Result
			= link_to edit_poll_result_path(@poll, @result), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @result.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.firstname")
			.display-value= @result.firstname
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.lastname")
			.display-value= @result.lastname
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.email")
			.display-value= @result.email
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.poll_id")
			.display-value= @result.poll_id


:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/results/_listing.html.haml
%tr{ id: "row-#{result.id}" }
	- if can? :destroy_multiple, Result
		%td.item-check{style:"width: 10%"}
			= link_to "", poll_result_path(@poll, result), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{result.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{result.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{result.id}" }

	%td{style:"width: 30%"}
		= link_to "", poll_result_path(@poll, result, search: @query), remote: true, class: "show-row"
		%span
			= result.firstname
	%td{style:"width: 30%"}
		= link_to "", poll_result_path(@poll, result, search: @query), remote: true, class: "show-row"
		%span
			= result.lastname
	%td{style:"width: 30%"}
		= link_to "", poll_result_path(@poll, result, search: @query), remote: true, class: "show-row"
		%span
			= result.email

	%td{style:"width: 5%"}
		= link_to poll_result_path(@poll, result), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/results/edit.html.haml
= title "Results - editar | #{@result.id}"
= render 'form'

app/views/results/index.html.haml
= title("Results - Listado")
= header_information do
	= link_to "#{@poll.name}", polls_path
	= "> Resultados"
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_poll_result_path(@poll), class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |result|
				= render 'listing', result: result
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado results.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_poll_result_path(@poll), class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/results/new.html.haml
= title "Results - Nuevo"
= render 'form'

app/views/results/show.html.haml
= title "Results | #{@result.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Result
				= link_to poll_result_path(@poll, @result), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Result
				= link_to edit_poll_result_path(@poll, @result), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to poll_results_path(@poll), class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.firstname")
					.display-value.fs-body-1.tc-black-2= @result.firstname.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.lastname")
					.display-value.fs-body-1.tc-black-2= @result.lastname.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.email")
					.display-value.fs-body-1.tc-black-2= @result.email.to_s.humanize
				- @result.results_questions.each do |result|
					%li.list-row
						.display-label= result.question.sentence
						.display-value.fs-body-1.tc-black-2= result.option

app/views/results/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@result.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");