config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|es/ do
    root to: 'frontend#index'

    devise_for :users, skip: KepplerConfiguration.skip_module_devise

    resources :admin, only: :index

    get "/eventos" => 'events#new', :as => :new_event
    post "/eventos" => 'events#create', :as => :create_events
    get "/paraguana" => "frontend#paraguana" , as: :paraguana
    get "/instalaciones" => "frontend#facilities" , as: :facilities
    get "/room/:permalink" => 'frontend#show_room' , as: :show_room
    get "/encuesta" => 'frontend#poll', :as => :new_poll
    post "/enviar_encuesta" => 'frontend#send_poll', :as => :send_poll

    scope :admin do
      resources :polls do
        get '/statistics', to: "polls#poll_statistics", as: :statistics
        get '/question/create/:question_type', to: "questions#create", as: :question_create
        delete '/question/delete/:id', to: "questions#delete", as: :question_delete
        get '/question/edit/:id/', to: "questions#edit", as: :question_edit
        delete '/question/:id/delete_option/:option_id', to: "questions#delete_option", as: :question_delete_option
        post '/question/:id/add_option/', to: "questions#add_option", as: :question_add_option
        patch '/question/update/:id/', to: "questions#update", as: :question
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple

        resources :results do
          get '(page/:page)', action: :index, on: :collection, as: ''
          delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
        end
      end

    	resources :users do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :rooms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      get 'clients/export' => 'clients#export', as: :export_clients
      resources :clients do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :events, except: [:new, :create] do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/export', action: :export, as: :export
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :promos do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :event_images do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end


    #errors
    match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
    match '/404', to: 'errors#not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all


    #dashboard
    mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'
  end

end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  layout 'layouts/frontend/application'
  before_action :set_urls

  def index
    @rooms = Room.with_translations(params[:locale] || 'es')
    @rooms = @rooms.reject { |room| room.images.empty? }
    @promo = Promo.find_by public: true
  end

  def paraguana
  end

  def facilities
  end

  def show_room
    @modal_opened = true if params[:modal_opened]
    @room = Room.find_by_permalink params[:permalink]

    respond_to do |format|
      format.js
    end
  end

  def poll
    lang = params[:locale].eql?("en") ? "en" : "es"
    @poll = Poll.find_by_language(lang)
  end

  def send_poll
    result_info = Result.create(build_result)
    results = params.to_a[5..(params.to_a.count-5)]
    results.each do |result|
      build_option(result_info, result)
    end
    redirect_to root_path
  end

  private
  def set_urls
    @reserva = 'http://paraguanamallhotel.com/booking'
    @twitter = 'https://twitter.com/pm_hotel'
    @tripadvisor = 'https://www.tripadvisor.com.ve/Hotel_Review-g316095-d5789162-Reviews-Paraguana_Mall_Hotel-Punto_Fijo_Paraguana_Peninsula_Central_Western_Region.html'
    @facebook = 'https://www.facebook.com/Paraguan%C3%A1-Mall-Hotel-162360603915332'
    @instagram = 'https://www.instagram.com/paraguanamallhotel/'
  end

  def build_result
    {
      firstname: params[:firstname],
      lastname: params[:lastname],
      email: params[:email],
      poll_id: Poll.where(public: true).first.id
    }
  end

  def build_option(result_info, result)
    if result.second.class == ActiveSupport::HashWithIndifferentAccess
      option = result.to_a.second
      if option.first.first.eql?("answer")
        add_result(option.first.second, result_info.id, result.first)
      else
        option.each do |item|
          add_result(item.first, result_info.id, result.first) if !item.eql?("on")
        end
      end
    else
      add_result(result.second, result_info.id, result.first)
    end
  end

  def add_result(option, result_id, question_id)
    ResultsQuestion.create(option: option, result_id: result_id, question_id: question_id)
  end
end

app/views/layouts/frontend/_footer.html.haml
%footer
  .map
    #map
    .contacts
      .contact-text
        %span= t('footer.location1')
        %span{ style: 'margin-bottom: 5px;' }= t('footer.location2')
        %span (+58) 269 3911831 / (+58) 269 391 1800
        %span reservaciones@paraguanamallhotel.com

  .rights
    = t('footer.rights')
  .slice
    = t('footer.slice')
    = link_to 'http://slicegroup.xyz/', target: '_blank' do
      = image_tag 'frontend/slicegroup.png'

app/views/layouts/frontend/_google_analytics.html.haml
- if Rails.env.production?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-78898359-1', 'auto');
    ga('send', 'pageview');

app/views/layouts/frontend/_head.html.haml
%head
  %meta{ name: 'viewport', content: "width=device-width, initial-scale=1.0" }
  %title= content_for?(:title) ? yield(:title) : "#{ t('landing.hotel') }"
  %meta{ name: 'description', content: "#{content_for?(:description) ? yield(:description) : t('meta_description')}" }
  %meta{:content => "#dca540", :name => "theme-color"}
  %meta{:content => "#dca540", :name => "msapplication-navbutton-color"}
  %meta{:content => "#dca540", :name => "apple-mobile-web-app-status-bar-style"}/
  %script{src:"https://maps.googleapis.com/maps/api/js?sensor=false"}
  = stylesheet_link_tag 'frontend/application', media: 'all', :'data-turbolinks-track' => true
  = javascript_include_tag 'frontend/application', :'data-turbolinks-track' => true
  = render 'layouts/frontend/google_analytics'
  = favicon_link_tag 'frontend/favicon.png'
  = csrf_meta_tags

app/views/layouts/frontend/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", onclick: "hideAlert();" }
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/frontend/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top#front-navbar
  .container
    .navbar-header
      %button.navbar-toggle{ type: 'button', data: { target: '.navbar-collapse', toggle: 'collapse' } }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .brand-logo
        = link_to root_path do
          = image_tag 'frontend/Landing/Logo.png'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.links-nav
        = render 'layouts/frontend/navigation_links'
      %ul.nav.navbar-nav.socials-nav
        = render 'layouts/frontend/social_links'

app/views/layouts/frontend/_navigation_links.html.haml
%li#link-about{ onclick: "scrollToAnchor('about')" }
  - if action_name == 'index'
    %a= t('navbar.home')
  - else
    = link_to root_path(anchor: 'about'), class: 'external' do
      = t('navbar.home')
%li#link-rooms{ onclick: "scrollToAnchor('rooms')" }
  - if action_name == 'index'
    %a= t('navbar.rooms')
  - else
    = link_to root_path(anchor: 'rooms'), class: 'external' do
      = t('navbar.rooms')
%li{ class: "#{ 'current' if controller_name == 'events' }" }
  = link_to t('navbar.events'), new_event_path
%li{ class: "#{ 'current' if action_name == 'facilities' }" }
  = link_to t('navbar.facilities'), facilities_path
%li{ class: "#{ 'current' if action_name == 'paraguana' }" }
  = link_to t('navbar.paraguana'), paraguana_path

app/views/layouts/frontend/_social_links.html.haml
%li.lenguage-tab
  .center
    = link_to "EN", { :locale => "en" }, class: "#{I18n.locale == :en ? ('locale active';) : ('locale';)}", "data-no-turbolink" => true
    |
    = link_to "ES", { :locale => "es" }, class: "#{I18n.locale == :es ? ('locale active';) : ('locale';)}", "data-no-turbolink" => true

%li
  = link_to @tripadvisor, class: 'socials', target: '_blank' do
    .center
      %i.fa.fa-tripadvisor
%li
  = link_to @twitter, class: 'socials', target: '_blank' do
    .center
      %i.fa.fa-twitter
%li
  = link_to @facebook, class: 'socials', target: '_blank' do
    .center
      %i.fa.fa-facebook
%li
  = link_to @instagram, class: 'socials', target: '_blank' do
    .center
      %i.fa.fa-instagram

app/views/layouts/frontend/application.html.haml
!!!
%html
  = render 'layouts/frontend/head'
  %body
    %header
      = render 'layouts/frontend/navigation'
    %main{ role: 'main' }
      = render 'layouts/frontend/messages'
      = yield
      = render 'layouts/frontend/footer'