config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|es/ do
    root to: 'frontend#index'

    devise_for :users, skip: KepplerConfiguration.skip_module_devise

    resources :admin, only: :index

    get "/eventos" => 'events#new', :as => :new_event
    post "/eventos" => 'events#create', :as => :create_events
    get "/paraguana" => "frontend#paraguana" , as: :paraguana
    get "/instalaciones" => "frontend#facilities" , as: :facilities
    get "/room/:permalink" => 'frontend#show_room' , as: :show_room
    get "/encuesta" => 'frontend#poll', :as => :new_poll
    post "/enviar_encuesta" => 'frontend#send_poll', :as => :send_poll

    scope :admin do
      resources :polls do
        get '/statistics', to: "polls#poll_statistics", as: :statistics
        get '/question/create/:question_type', to: "questions#create", as: :question_create
        delete '/question/delete/:id', to: "questions#delete", as: :question_delete
        get '/question/edit/:id/', to: "questions#edit", as: :question_edit
        delete '/question/:id/delete_option/:option_id', to: "questions#delete_option", as: :question_delete_option
        post '/question/:id/add_option/', to: "questions#add_option", as: :question_add_option
        patch '/question/update/:id/', to: "questions#update", as: :question
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple

        resources :results do
          get '(page/:page)', action: :index, on: :collection, as: ''
          delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
        end
      end

    	resources :users do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :rooms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      get 'clients/export' => 'clients#export', as: :export_clients
      resources :clients do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :events, except: [:new, :create] do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/export', action: :export, as: :export
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :promos do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :event_images do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end


    #errors
    match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
    match '/404', to: 'errors#not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all


    #dashboard
    mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'
  end

end

app/models/promo.rb
#Generado por keppler
require 'elasticsearch/model'
class Promo < ActiveRecord::Base
  require 'file_size_validator'
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  before_save :set_public
  mount_uploader :image, PromoUploader
  validates_presence_of :name, :image
  validates_uniqueness_of :name

  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      image:  self.image.to_s,
      name:  self.name.to_s,
      public:  self.public.to_s,
    }.as_json
  end

  def set_public
    Promo.update_all(public: false) if self.public
  end
end
#Promo.import

app/controllers/promos_controller.rb
#Generado con Keppler.
class PromosController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  def index
    promos = Promo.searching(@query).all
    @objects, @total = promos.page(@current_page), promos.size
    redirect_to promos_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /promos/1
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  def create
    @promo = Promo.new(promo_params)

    if @promo.save
      redirect_to @promo, notice: 'Promo was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /promos/1
  def update
    if @promo.update(promo_params)
      redirect_to promos_path, notice: 'Promo was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /promos/1
  def destroy
    @promo.destroy
    redirect_to promos_url, notice: 'Promo was successfully destroyed.'
  end

  def destroy_multiple
    Promo.destroy redefine_ids(params[:multiple_ids])
    redirect_to promos_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def promo_params
      params.require(:promo).permit(:image, :name, :public)
    end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_description.html.haml
.listing-show-header
  %h5
    = material_icon.md_24.account_circle.css_class("md-light")
    = t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
  .list
    %h5= t('header.module_description')
    %p{align: "justify"}= t('descriptions.promos.text1')
    %p{align: 'justify'}= t('descriptions.promos.text2')
    %p{style: 'text-align: center; font-weight: bold;'}= t('descriptions.promos.text3')

app/views/promos/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to promos_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t('tooltip.back') do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @promo do |f|
					.row
						= f.input :name, label: t("model.promo.attributes.name")
						= f.input :image, :as => :file_material, label: false, wrapper_html: { class: "file-field" }
						= f.input :public, as: :checkbox_material, label: t("model.promo.attributes.public")

						.form-actions.right
							= f.button :submit, t('buttons.save'), class: "btn"

app/views/promos/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Promo
			= link_to edit_promo_path(@promo), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t('tooltip.edit') do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	= image_tag @promo.image
	%ul.list
		%li.list-row
			.display-label{ style: 'text-align: center;' }= @promo.public ? t('model.promo.public_true') : t('model.promo.public_false')
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @promo.name


:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/promos/_listing.html.haml
%tr{ id: "row-#{promo.id}" }
	- if can? :destroy_multiple, Promo
		%td.item-check{style:"width: 10%"}
			= link_to "", promo_path(promo), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{promo.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{promo.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{promo.id}" }

		%td{style:"width: 30%"}
			= link_to "", promo_path(promo, search: @query), remote: true, class: "show-row"
			%span
				= promo.name
		%td{style:"width: 30%"}
			= link_to "", promo_path(promo, search: @query), remote: true, class: "show-row"
			%span
				= promo.public ? t('model.promo.public_true') : t('model.promo.public_false')
		%td{ style: 'width: 10%' }
			= render 'promos/public_switch', promo: promo

	%td{style:"width: 5%"}
		= link_to promo_path(promo), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/promos/_public_switch.html.haml
= simple_form_for promo do |f|
  .switch
    %label
      - if f.object.public == false
        %input{name: "promo[public]", type: "hidden", value: "true"}
        %input{name: "promo[public]", type: "checkbox", onclick: "$('#edit_promo_#{promo.id}').submit()"}
          %span.lever

      - else
        %input{name: "promo[public]", type: "hidden", value: "false"}
        %input{name: "promo[public]", type: "checkbox", onclick: "$('#edit_promo_#{promo.id}').submit()", checked: "true"}
          %span.lever

app/views/promos/edit.html.haml
= title "#{ t('model.singular.promo') } - #{ t('actions.edit') } | #{@promo.name}"
= render 'form'

app/views/promos/index.html.haml
= title "#{ t('model.plural.promos') } - #{ t('actions.index') } "
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_promo_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |promo|
				= render 'listing', promo: promo
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('model.promo.no_promos')
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_promo_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/promos/new.html.haml
= title "#{ t('model.singular.promo') } - #{ t('actions.new') } "
= render 'form'

app/views/promos/show.html.haml
= title "#{ t('model.singular.promo') } | #{@promo.name}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Promo
				= link_to promo_path(@promo), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t('tooltip.delete'), method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Promo
				= link_to edit_promo_path(@promo), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t('tooltip.edit') do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to promos_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t('tooltip.back') do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-image
				= image_tag @promo.image
			%ul.list
				%li.list-row
					.display-label{ style: 'text-align: center;' }= @promo.public ? t('model.promo.public_true') : t('model.promo.public_false')
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @promo.name.to_s.humanize

app/views/promos/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@promo.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");