config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|es/ do
    root to: 'frontend#index'

    devise_for :users, skip: KepplerConfiguration.skip_module_devise

    resources :admin, only: :index

    get "/eventos" => 'events#new', :as => :new_event
    post "/eventos" => 'events#create', :as => :create_events
    get "/paraguana" => "frontend#paraguana" , as: :paraguana
    get "/instalaciones" => "frontend#facilities" , as: :facilities
    get "/room/:permalink" => 'frontend#show_room' , as: :show_room
    get "/encuesta" => 'frontend#poll', :as => :new_poll
    post "/enviar_encuesta" => 'frontend#send_poll', :as => :send_poll

    scope :admin do
      resources :polls do
        get '/statistics', to: "polls#poll_statistics", as: :statistics
        get '/question/create/:question_type', to: "questions#create", as: :question_create
        delete '/question/delete/:id', to: "questions#delete", as: :question_delete
        get '/question/edit/:id/', to: "questions#edit", as: :question_edit
        delete '/question/:id/delete_option/:option_id', to: "questions#delete_option", as: :question_delete_option
        post '/question/:id/add_option/', to: "questions#add_option", as: :question_add_option
        patch '/question/update/:id/', to: "questions#update", as: :question
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple

        resources :results do
          get '(page/:page)', action: :index, on: :collection, as: ''
          delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
        end
      end

    	resources :users do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :rooms do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      get 'clients/export' => 'clients#export', as: :export_clients
      resources :clients do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :events, except: [:new, :create] do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/export', action: :export, as: :export
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :promos do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end

      resources :event_images do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end


    #errors
    match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
    match '/404', to: 'errors#not_found', via: :all
    match '/422', to: 'errors#unprocessable', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all


    #dashboard
    mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'
  end

end

app/models/room.rb
#Generado por keppler
require 'elasticsearch/model'
class Room < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  before_save :create_permalink
  has_many :images, :dependent => :destroy
  has_many :reservations, through: :orders
  has_many :orders
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
  validates_presence_of :name, :price, :description, on: :update
  validates_uniqueness_of :name
  translates :name, :description
  validate :images_present?, on: :update
  validates :images, presence: true, on: :update

  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:id, :name, :price, :description] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name,
      price:  self.price.to_s,
      description:  self.description,
    }.as_json
  end

  def create_permalink
    self.permalink=self.name.downcase.parameterize
  end

  def images_present?
    errors.add(:description, 'Debe agregar imágenes') if images.empty?
  end

end

#Room.import

app/controllers/rooms_controller.rb
#Generado con Keppler.
class RoomsController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_room, only: [:show, :edit, :update, :edit_room_images, :update_room_images, :destroy]

  # GET /rooms
  def index
    rooms = Room.searching(@query).all
    @objects, @total = rooms.page(@current_page), rooms.size
    redirect_to rooms_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /rooms/1
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room, notice: 'Habitación creada satisfactoriamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /rooms/1
  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Habitación editada satisfactoriamente.'
    else
      render :edit
    end
  end



  # DELETE /rooms/1
  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Habitación eliminada satisfactoriamente.'
  end

  def destroy_multiple
    Room.destroy redefine_ids(params[:multiple_ids])
    redirect_to rooms_path(page: @current_page, search: @query), notice: "Habitaciones eliminadas satisfactoriamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def room_params
      params.require(:room).permit(:name, :price, :description, images_attributes: [:id, :img, :_destroy])
    end
end

app/views/rooms/_description.html.haml
.listing-show-header
  %h5
    = material_icon.md_24.account_circle.css_class("md-light")
    = t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
  .list
    %h5= t('header.module_description')
    %p{align: "justify"}= t('descriptions.rooms')

app/views/rooms/_form.html.haml
.wrapper
  .wrapper-body.container
    .actions
      = link_to rooms_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t('tooltip.back') do
        = material_icon.md_18.arrow_back.css_class("md-dark")

    .wrapper-inputs
      .card
        = simple_form_for @room do |f|
          .row
            = f.input :name
            = f.input :price
            = f.input :description, :as => :ckeditor, label: false, input_html: {:ckeditor => { :toolbar => 'mini'} ,class: "materialize-textarea"}
          .row
            = f.simple_fields_for :images do |c|
              = render 'image_fields', :f => c
            .form-actions.right
              = link_to_add_association t('buttons.add_img'), f, :images, class: "waves-effect waves-dark btn-flat"
              = f.button :submit, t('buttons.save'), class: "btn"

app/views/rooms/_image_fields.html.haml
.nested-fields.col.s12
  %ul.collection
    %li.collection-item.avatar
      %img.circle{:src => "#{f.object.img.thumb unless f.object.img.to_s == ''}", id: "circle-#{f.object.id}"}
        = f.input :img, :as => :file_material, label: false, wrapper_html: { class: "file-field input-#{f.object.id}"}
        .secondary-content
          = link_to_remove_association f do
            = material_icon.md_24.close.css_class('md-dark')
        :javascript
          src = $('#circle-#{f.object.id}').attr('src').split('thumb_')[1]
          $('.input-#{f.object.id}').find('.file-path').val(src)

app/views/rooms/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Room
			= link_to edit_room_path(@room), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t('tooltip.edit') do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	- if @room.images.any?
		= image_tag @room.images.first.img
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @room.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @room.name.nil? ? t('model.room.attributes.no_translation')  : @room.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.price")
			.display-value= number_to_currency(@room.price, precision: 2, format: "%u %n", unit: "Bs.")
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @room.description.nil? ? t('model.room.attributes.no_translation') : @room.description.html_safe






:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/rooms/_listing.html.haml
%tr{ id: "row-#{room.id}" }
	- if can? :destroy_multiple, Room
		%td.item-check{style:"width: 10%"}
			= link_to "", room_path(room), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{room.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{room.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{room.id}" }

	%td{style:"width: 30%"}
		= link_to "", room_path(room, search: @query), remote: true, class: "show-row"
		%span
			= room.name.nil? ? t('model.room.attributes.no_translation') : room.name
	%td{style:"width: 30%"}
		= link_to "", room_path(room, search: @query), remote: true, class: "show-row"
		%span
			= number_to_currency(room.price, precision: 2, format: "%u %n", unit: "Bs.")

	%td{style:"width: 5%"}
		= link_to room_path(room), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/rooms/edit.html.haml
= title "#{ t('model.plural.rooms') } - #{ t('actions.new') } | #{@room.name}"
= render 'form'

app/views/rooms/index.html.haml
= title "#{ t('model.plural.rooms') } - #{ t('actions.index') } "
.listing.col.l9.m12.s12
	- if can?(:new, model) && @objects.count < 4
		= link_to new_room_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |room|
				= render 'listing', room: room
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('model.room.no_rooms')
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

app/views/rooms/new.html.haml
= title  "#{ t('model.plural.rooms') } - #{ t('actions.new') } "
= render 'form'

app/views/rooms/show.html.haml
= title "#{ t('model.plural.rooms') } | #{@room.name}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Room
				= link_to room_path(@room), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t('tooltip.delete'), method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Room
				= link_to edit_room_path(@room), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t('tooltip.edit') do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to rooms_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t('tooltip.back') do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card#show-room
			- if @room.images.any?
				.card-image
					.slider
						%ul.slides
							- @room.images.each do |item|
								%li
									= image_tag item.img

			.card-content
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.id")
						.display-value.fs-body-1.tc-black-2= @room.id.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @room.name.nil? ? t('model.room.attributes.no_translation')  : @room.name
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.price")
						.display-value.fs-body-1.tc-black-2= number_to_currency(@room.price, precision: 2, format: "%u %n", unit: "Bs.")
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.description")
						.display-value.fs-body-1.tc-black-2= @room.description.nil? ? t('model.room.attributes.no_translation') : @room.description.html_safe


:javascript
	$(document).ready(function(){
		$('.slider').slider();
	});

app/views/rooms/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@room.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");